---
apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  releaseName: crossplane
  chart:
    repository: https://charts.crossplane.io/master/
    name: crossplane
    version: 1.0.0
  values:
    image:
      repository: crossplane/crossplane
      tag: v1.1.0
    leaderElection: false
    rbacManager:
      deploy: false
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: default
  namespace: crossplane-system
spec:
  package: crossplane/provider-aws:master
---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::575558793282:role/role-eks-crossplane
spec:
  podSecurityContext:
    fsGroup: 2000
---